export interface KotaeItem {
  title: string;
  url: string;
}

export const KOTAE_LIST: KotaeItem[] = [
  { title: "Q2003봐서는vs보니까", url: "https://kotae.mirinae.jp/q/bwaseoneun-bonikka" },
  { title: "Q2002～고 그러지 말라 vs ～지 말라", url: "https://kotae.mirinae.jp/q/gora-geuraeji-malla" },
  { title: "Q2001소원と소망の違いが分からず困っています。", url: "https://kotae.mirinae.jp/q/sowon-somang" },
  { title: "Q1005「メールで返事してほしいです。」を韓国語にすると？", url: "https://kotae.mirinae.jp/q/quiz1" },
  { title: "Q1004「そうするわけにはいきません」を韓国語にすると？", url: "https://kotae.mirinae.jp/q/quiz2" },
  { title: "Q1003「なんでそんなことを言うの？」を韓国語にすると？", url: "https://kotae.mirinae.jp/q/quiz3" },
  { title: "Q1002「それでも僕はやっていない」を韓国語にすると", url: "https://kotae.mirinae.jp/q/quiz4" },
  { title: "Q1001「その店は学生時代によく行っていました」を韓国語にすると？", url: "https://kotae.mirinae.jp/q/quiz5" },
  { title: "Q1「할 수 밖에 없다」 と 「하는 수 밖에 없다」の違いについて", url: "https://kotae.mirinae.jp/q/1" },
  { title: "Q2「할 거예요」 と 「하는 거예요」の違いは？", url: "https://kotae.mirinae.jp/q/2" },
  { title: "Q3「노래를 하다」と「노래를 부르다」の違いは。", url: "https://kotae.mirinae.jp/q/3" },
  { title: "Q4-어 있다 vs -고 있다 の使い分けが難しいです。", url: "https://kotae.mirinae.jp/q/4" },
  { title: "Q5-기 때문에 vs 니까 vs 는데 違いはなんですか?", url: "https://kotae.mirinae.jp/q/5" },
  { title: "Q6否定の表現で\"안~\"と\"~지 않다\"はどう違いますか？", url: "https://kotae.mirinae.jp/q/6" },
  { title: "Q7「볶다 炒める」と 「부치다 焼く」の違いは何でしょうか。", url: "https://kotae.mirinae.jp/q/7" },
  { title: "Q8「누구든지」と「누구라도」と 「누구나」は完全に同じ意味でしょうか。", url: "https://kotae.mirinae.jp/q/8" },
  { title: "Q9'-해 버리다' と '-하고 말다'の違いを説明してください。", url: "https://kotae.mirinae.jp/q/9" },
  { title: "Q10'먹을 만하다（食べれる）'と'먹기에 괜찮다（食べるのにいい）'の違いは何でしょうか。", url: "https://kotae.mirinae.jp/q/10" },
  { title: "Q11'-ㄹ 줄 몰랐다（－とは思わなかった）'と'-ㄴ 줄 몰랐다'の違いは何でしょうか。", url: "https://kotae.mirinae.jp/q/11" },
  { title: "Q12'-했더니'と '-싶더니'の違いは何ですか。", url: "https://kotae.mirinae.jp/q/12" },
  { title: "Q13무슨 일 있었어? /어쩐일이에요? /웬일이에요? /왜 그래? /왜 이래?の使い方について教えてください。", url: "https://kotae.mirinae.jp/q/13" },
  { title: "Q14会話で語尾に뭐が付く表現をよく聞きますが", url: "https://kotae.mirinae.jp/q/14" },
  { title: "Q15한국에서は/한구게서/と発音するのに、한국 여행はどうして/한궁녀행/になるんですか？", url: "https://kotae.mirinae.jp/q/15" },
  { title: "Q16오죽하다,오죽하면,오죽하겠어について教えてください。", url: "https://kotae.mirinae.jp/q/16" },
  { title: "Q17~에요 と ~예요 二つの中でどれを使えばいいですか。", url: "https://kotae.mirinae.jp/q/17" },
  { title: "Q18'같다' と'마찬가지다'の違いは何ですか。", url: "https://kotae.mirinae.jp/q/18" },
  { title: "Q19語尾がむずかしいです。どういう場合に「～거든요」を使うのか今いちよくわかりません。", url: "https://kotae.mirinae.jp/q/19" },
  { title: "Q20'에'と'로'の使い方がわかりません。", url: "https://kotae.mirinae.jp/q/20" },
  { title: "Q21알다, 알겠다はどう違うでしょうか。", url: "https://kotae.mirinae.jp/q/21" },
  { title: "Q22살고 있다と살아 있다をよく間違えます。", url: "https://kotae.mirinae.jp/q/22" },
  { title: "Q23'겠'の活用がいまだに分かりません。", url: "https://kotae.mirinae.jp/q/23" },
  { title: "Q24숙제 하느라 바빴다と숙제 하기 때문에 바빴다の違いは？", url: "https://kotae.mirinae.jp/q/24" },
  { title: "Q25~고 말다 と ~아(어) 버리다の使い方に違いはありますか？", url: "https://kotae.mirinae.jp/q/25" },
  { title: "Q26｢良かった｣という意味の表現は'좋았다,잘됐다,잘 했다,다행이다'など似ている表現がたくさんあって難しいです。", url: "https://kotae.mirinae.jp/q/26" },
  { title: "Q27-해서と-하고の違いについて教えてください。", url: "https://kotae.mirinae.jp/q/27" },
  { title: "Q28~보면と~보니까の使い方がよくわかりません。", url: "https://kotae.mirinae.jp/q/28" },
  { title: "Q29韓国語単語の中で、縮約形について教えてください", url: "https://kotae.mirinae.jp/q/29" },
  { title: "Q30얼른, 빨리, 일찍, 어서 どうやって使い分けますか？", url: "https://kotae.mirinae.jp/q/30" },
  { title: "Q31気になる＝「궁금하다」「마음에 걸리다 」「신경을 쓰다」？", url: "https://kotae.mirinae.jp/q/31" },
  { title: "Q32이미 vs 벌써 どう違う？", url: "https://kotae.mirinae.jp/q/32" },
  { title: "Q33動詞の名詞化する기、ㅁ、이の使い方は違うのでしょうか？", url: "https://kotae.mirinae.jp/q/33" },
  { title: "Q34아주, 매우, 너무, 정말, 진짜, 참, 가장, 제일はどう違いますか？", url: "https://kotae.mirinae.jp/q/34" },
  { title: "Q35'~ㄹ 거예요 vs '~ㄹ게요'", url: "https://kotae.mirinae.jp/q/35" },
  { title: "Q36-면と-려면はどう違いますか", url: "https://kotae.mirinae.jp/q/36" },
  { title: "Q37「물론이지요」「그럼요」の違いを教えて下さい。", url: "https://kotae.mirinae.jp/q/37" },
  { title: "Q38-탓에 vs -므로 使い方に違いはありますか？", url: "https://kotae.mirinae.jp/q/38" },
  { title: "Q39놓다 vs 두다 どう違いますか？", url: "https://kotae.mirinae.jp/q/39" },
  { title: "Q40해요?、할까요?、할래요?の違いは何ですか？", url: "https://kotae.mirinae.jp/q/40" },
  { title: "Q41―와・과と―하고と―랑はどう違いますか？", url: "https://kotae.mirinae.jp/q/41" },
  { title: "Q42「～から」に当たる表現で「(으)로부터」「에서부터」の使い分けは？", url: "https://kotae.mirinae.jp/q/42" },
  { title: "Q43매다 VS 메다 '넥타이를 매다'ですか、'메다'ですか。", url: "https://kotae.mirinae.jp/q/43" },
  { title: "Q44버스를 타다 vs 버스에 타다?", url: "https://kotae.mirinae.jp/q/44" },
  { title: "Q45여행에 가다？ 여행을 가다？", url: "https://kotae.mirinae.jp/q/45" },
  { title: "Q46「는지」「든지」「을지」の使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/46" },
  { title: "Q47'줄줄' '술술' '척척' の違いは?", url: "https://kotae.mirinae.jp/q/47" },
  { title: "Q48다르다 vs 틀리다 はどう違いますか。", url: "https://kotae.mirinae.jp/q/48" },
  { title: "Q491.기대한 만큼 VS 2.기대했던 만큼 の違いは？", url: "https://kotae.mirinae.jp/q/49" },
  { title: "Q50きれいの意味で「예쁘다 vs 곱다」どんな差がありますか。", url: "https://kotae.mirinae.jp/q/50" },
  { title: "Q51진 만큼vsー질 만큼どう違いますか。", url: "https://kotae.mirinae.jp/q/51" },
  { title: "Q52만약と혹시どう違う?", url: "https://kotae.mirinae.jp/q/52" },
  { title: "Q53「지 않다」の連体形について教えてください。", url: "https://kotae.mirinae.jp/q/53" },
  { title: "Q54-라고 생각해요 vs -ㄴ 것 같아요 はどう違いますか？", url: "https://kotae.mirinae.jp/q/54" },
  { title: "Q55괜찮아요? vs 괜찮겠어요? の違いがよく分かりません。", url: "https://kotae.mirinae.jp/q/55" },
  { title: "Q56-고 있는 vs – 아/어 있는の違いは？", url: "https://kotae.mirinae.jp/q/56" },
  { title: "Q57[-ㄹ줄 알다/모르다 vs -ㄹ수 있다]の違いは？", url: "https://kotae.mirinae.jp/q/57" },
  { title: "Q58섭섭하다 vs 아쉽다 ニュアンスの差がありますか。", url: "https://kotae.mirinae.jp/q/58" },
  { title: "Q59기르다 vs 키우다 どう違いますか。", url: "https://kotae.mirinae.jp/q/59" },
  { title: "Q60-해 보니 vs -해 보면 を説明してください。", url: "https://kotae.mirinae.jp/q/60" },
  { title: "Q61動詞の過去連体形 은 VS 던 VS 었던 の違いは何ですか。", url: "https://kotae.mirinae.jp/q/61" },
  { title: "Q62-야지のニュアンスについて教えてください。", url: "https://kotae.mirinae.jp/q/62" },
  { title: "Q63-거예요 vs -려고 해요 vs -라고 생각해요はどう違いますか。", url: "https://kotae.mirinae.jp/q/63" },
  { title: "Q64(雪、雨) 내리다 vs 오다 vs 떨어지다どう違いますか？", url: "https://kotae.mirinae.jp/q/64" },
  { title: "Q65-더니 と-었더니 １人称？3人称？", url: "https://kotae.mirinae.jp/q/65" },
  { title: "Q66-더라のニュアンスについて教えてください。", url: "https://kotae.mirinae.jp/q/66" },
  { title: "Q67道を聞かれた際、모릅니다と모르겠어요 どっちを使いますか？", url: "https://kotae.mirinae.jp/q/67" },
  { title: "Q68\"부끄럽다\"と \"쑥스럽다\"と창피하다はどう違いますか?", url: "https://kotae.mirinae.jp/q/68" },
  { title: "Q69\"올라가더니\"の使い方を教えてください。", url: "https://kotae.mirinae.jp/q/69" },
  { title: "Q70만들다と시키다の使役を教えてください。", url: "https://kotae.mirinae.jp/q/70" },
  { title: "Q71-ㄹ지라도vs-더라도vs-건の違いは？", url: "https://kotae.mirinae.jp/q/71" },
  { title: "Q72「아/어 지다」vs「게 되다」の使い分けが難しいです。", url: "https://kotae.mirinae.jp/q/72" },
  { title: "Q73그치다 vs 멈추다 vs 멎다の違いを教えてください。", url: "https://kotae.mirinae.jp/q/73" },
  { title: "Q74변하다 vs 바뀌다 どう違うんですか？", url: "https://kotae.mirinae.jp/q/74" },
  { title: "Q75－ての-고vs-아・어서に使い分けが難しいです。", url: "https://kotae.mirinae.jp/q/75" },
  { title: "Q76英語の韓国語表記が難しいです。決まりってあるのですか。", url: "https://kotae.mirinae.jp/q/76" },
  { title: "Q77단지 vs 그저 vs 그냥の違いを教えてください。", url: "https://kotae.mirinae.jp/q/77" },
  { title: "Q78늘 vs 언제나 vs 항상はまったく同じ意味ですか。", url: "https://kotae.mirinae.jp/q/78" },
  { title: "Q79가 있었다 と 갔었다 と갔다 は違うのですか。", url: "https://kotae.mirinae.jp/q/79" },
  { title: "Q80마음대로 하세요と알아서 하세요の違いは？", url: "https://kotae.mirinae.jp/q/80" },
  { title: "Q81차라리 VS 오히려の違いを教えてください。", url: "https://kotae.mirinae.jp/q/81" },
  { title: "Q82아니고と말고の使い方の違いは？", url: "https://kotae.mirinae.jp/q/82" },
  { title: "Q83덥군요と덥네요は同じですか？", url: "https://kotae.mirinae.jp/q/83" },
  { title: "Q84「그러나」、「그렇지만」、「그런」の違いは？", url: "https://kotae.mirinae.jp/q/84" },
  { title: "Q85\"제대로, 마음대로, 뜻대로\"は同じ意味ですか？", url: "https://kotae.mirinae.jp/q/85" },
  { title: "Q86아무튼、어쨌든 どっち使ってもいいですよね？", url: "https://kotae.mirinae.jp/q/86" },
  { title: "Q87「一番」の意味の 가장と제일は同じですか。", url: "https://kotae.mirinae.jp/q/87" },
  { title: "Q88느니, 다느니, 라든가, 니, 며はどういう風に使いますか？", url: "https://kotae.mirinae.jp/q/88" },
  { title: "Q89否定の表現で\"안~\"と\"~지 않다\"はどう違いますか？", url: "https://kotae.mirinae.jp/q/89" },
  { title: "Q90-만(도) 못하다, -느니만 못하다はどういう風に使いますか。", url: "https://kotae.mirinae.jp/q/90" },
  { title: "Q91거예요? vs 갈 건가요? vs 가지요? どう違うのでしょうか。", url: "https://kotae.mirinae.jp/q/91" },
  { title: "Q92다가の使い方よくわかりません。", url: "https://kotae.mirinae.jp/q/92" },
  { title: "Q93あらゆる推測表現を教えてください。", url: "https://kotae.mirinae.jp/q/93" },
  { title: "Q94「구하다」と「건지다」とは違いが あるのでしょうか？", url: "https://kotae.mirinae.jp/q/94" },
  { title: "Q95속이 안 좋다の속は何ですか。", url: "https://kotae.mirinae.jp/q/95" },
  { title: "Q96～ㄹ망정と、～ㄹ지언정の違いを教えてください。", url: "https://kotae.mirinae.jp/q/96" },
  { title: "Q97힘들다 vs 어렵다の使い分けが難しいです。", url: "https://kotae.mirinae.jp/q/97" },
  { title: "Q98즐겁다 vs 신나다の違いは？", url: "https://kotae.mirinae.jp/q/98" },
  { title: "Q99차갑다 vs 시원하다はどうやって使い分けますか？", url: "https://kotae.mirinae.jp/q/99" },
  { title: "Q100～(으)ㄹ 수도 있다 ～(으)ㄹ 지도 모른다 は同じ意味で使えますか？", url: "https://kotae.mirinae.jp/q/100" },
  { title: "Q101-다가と-아・어 다가と-았・었다가の区別が難しいです。", url: "https://kotae.mirinae.jp/q/101" },
  { title: "Q102해주라vs해달라の使い分けがよく分かりません。", url: "https://kotae.mirinae.jp/q/102" },
  { title: "Q103달다 vs 달콤하다はどうやって使い分けますか？", url: "https://kotae.mirinae.jp/q/103" },
  { title: "Q104딱딱하다 vs 단단하다の違いは？", url: "https://kotae.mirinae.jp/q/104" },
  { title: "Q105때때로、 가끔、 종종それぞれ使い分けはどうなりますか？", url: "https://kotae.mirinae.jp/q/105" },
  { title: "Q106「そうなんですね」 と「そうですね」両方とも \"그렇네요\"と言ってもいいですか。", url: "https://kotae.mirinae.jp/q/106" },
  { title: "Q107깨끗하다 vs 깔끔하다の使い分けは？", url: "https://kotae.mirinae.jp/q/107" },
  { title: "Q108갓 vs 막 vs 이제 vs 금방 vs 방금の使い分けは？", url: "https://kotae.mirinae.jp/q/108" },
  { title: "Q109「-에게」、「-한테」と「-에게서」、「-한테서」は何が違いますか。", url: "https://kotae.mirinae.jp/q/109" },
  { title: "Q110처럼と같은の違いを教えてください。", url: "https://kotae.mirinae.jp/q/110" },
  { title: "Q111「여성」はどういったときに使われますか？", url: "https://kotae.mirinae.jp/q/111" },
  { title: "Q112-아/어서vs-니까、どう違いますか？使い分けが分かりません。", url: "https://kotae.mirinae.jp/q/112" },
  { title: "Q113-ㄹ 것 같아vs-는 것 같아の違いは？", url: "https://kotae.mirinae.jp/q/113" },
  { title: "Q114「それはまぁ、いいんだけど…. 」の「まぁ」は、「뭐」でしょうか？", url: "https://kotae.mirinae.jp/q/114" },
  { title: "Q115ー니까のニュアンスを教えてください。", url: "https://kotae.mirinae.jp/q/115" },
  { title: "Q116オーディションも、보다 ですか？また、 보다に他の意味もありますか。", url: "https://kotae.mirinae.jp/q/116" },
  { title: "Q117아이と아기と애기はどう違いますか。", url: "https://kotae.mirinae.jp/q/117" },
  { title: "Q118とても辛くしてください。の、とても は、너무 많이 아주のどれが良いですか？", url: "https://kotae.mirinae.jp/q/118" },
  { title: "Q119어쩔 수 없어서と어쩔 수 없이はどう違いますか?", url: "https://kotae.mirinae.jp/q/119" },
  { title: "Q120다니요, (이)라니요と(이)기는요の違いを教えてください。", url: "https://kotae.mirinae.jp/q/120" },
  { title: "Q121\"ㄴ/ㄹ/는 줄 알다/모르다\"について質問です。", url: "https://kotae.mirinae.jp/q/121" },
  { title: "Q122쓰다vs적다どう違いますか。", url: "https://kotae.mirinae.jp/q/122" },
  { title: "Q123'-겠'が難しいです。使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/123" },
  { title: "Q124그렇다と그러다、그렇군요と그랬어요や그러지요の使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/124" },
  { title: "Q125「強い」の세다と강하다の使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/125" },
  { title: "Q126'또'と'다시'の違いはなんですか?", url: "https://kotae.mirinae.jp/q/126" },
  { title: "Q127-대요と거래요の違いを教えてください。", url: "https://kotae.mirinae.jp/q/127" },
  { title: "Q128혼자と혼자서はどう違いますか?", url: "https://kotae.mirinae.jp/q/128" },
  { title: "Q129「-(하)니」と「-ㅆ(했)더니」どんなニュアンスの違いがありますか？", url: "https://kotae.mirinae.jp/q/129" },
  { title: "Q130'-면 좋겠다' と '-ㅆ으면 좋겠다'はどう違いますか?", url: "https://kotae.mirinae.jp/q/130" },
  { title: "Q131-(는)다니요? の使い方を教えてください。", url: "https://kotae.mirinae.jp/q/131" },
  { title: "Q132「-거나-거나」と「-든가-든가」に違いはありますか？", url: "https://kotae.mirinae.jp/q/132" },
  { title: "Q133-토록は-도록と違いますか。", url: "https://kotae.mirinae.jp/q/133" },
  { title: "Q134～してからの意味の고 나서, ㄴ 후에, 면서부터, 어서부터 の使い分けが分かりません。", url: "https://kotae.mirinae.jp/q/134" },
  { title: "Q135웬일이야？と왜그래？とは同じ意味なんですか？", url: "https://kotae.mirinae.jp/q/135" },
  { title: "Q136가져 가다vs가지고 가다 どう違いますか？", url: "https://kotae.mirinae.jp/q/136" },
  { title: "Q137\"어떻게\"と\"어떡해\"はどう違いますか?", url: "https://kotae.mirinae.jp/q/137" },
  { title: "Q138①うまくできるさ②うまくいくさは韓国語で何ですか？", url: "https://kotae.mirinae.jp/q/138" },
  { title: "Q139~고 보니vs~아/어 보니 の違いはなんでしょうか。", url: "https://kotae.mirinae.jp/q/139" },
  { title: "Q140작정と예정の違いは何でしょうか？", url: "https://kotae.mirinae.jp/q/140" },
  { title: "Q141受身について詳しく教えてください。", url: "https://kotae.mirinae.jp/q/141" },
  { title: "Q142ことの意味の「것」と「일」の違いは何ですか。", url: "https://kotae.mirinae.jp/q/142" },
  { title: "Q143『띄어쓰기分かち書き』の ルールを教えてください。", url: "https://kotae.mirinae.jp/q/143" },
  { title: "Q144使役形について詳しく知りたいです。", url: "https://kotae.mirinae.jp/q/144" },
  { title: "Q145어제 밤 と어젯 밤どっちが正しいですか？", url: "https://kotae.mirinae.jp/q/145" },
  { title: "Q146이르다は'르変則'ですか、'러変則'ですか。", url: "https://kotae.mirinae.jp/q/146" },
  { title: "Q147가지다 と들다の違いを詳しく教えてください。", url: "https://kotae.mirinae.jp/q/147" },
  { title: "Q148いろんな間接話法について教えてください。", url: "https://kotae.mirinae.jp/q/148" },
  { title: "Q149모르는 척vs모른 척はどう違いますか。", url: "https://kotae.mirinae.jp/q/149" },
  { title: "Q150'できる'の色んな意味について教えてください。", url: "https://kotae.mirinae.jp/q/150" },
  { title: "Q151文型のなかで語幹に'~기'がつくものには何がありますか？", url: "https://kotae.mirinae.jp/q/151" },
  { title: "Q152함께と같이はどう違いますか。", url: "https://kotae.mirinae.jp/q/152" },
  { title: "Q153모두,전부,다 は同じ意味ですか？", url: "https://kotae.mirinae.jp/q/153" },
  { title: "Q154\"만\"がある文章とない文章の違いを教えてください。", url: "https://kotae.mirinae.jp/q/154" },
  { title: "Q155～면vs～더니はどう違いますか。", url: "https://kotae.mirinae.jp/q/155" },
  { title: "Q156곧vs바로の違いについて教えてくださあい。", url: "https://kotae.mirinae.jp/q/156" },
  { title: "Q157-던vs-았/었던の違いについて教えてください。", url: "https://kotae.mirinae.jp/q/157" },
  { title: "Q158아/어形を使っているさまざまな表現を教えてください。", url: "https://kotae.mirinae.jp/q/158" },
  { title: "Q159直訳すると不自然な助詞について教えてください。", url: "https://kotae.mirinae.jp/q/159" },
  { title: "Q160会話でよく使う縮約形についてまとめていただきたいのですが。", url: "https://kotae.mirinae.jp/q/160" },
  { title: "Q161引用文の縮約形について教えてください。", url: "https://kotae.mirinae.jp/q/161" },
  { title: "Q162～だけの～만と～뿐は同じですか。", url: "https://kotae.mirinae.jp/q/162" },
  { title: "Q163文末に그래요が付くと、どういう意味になりますか。", url: "https://kotae.mirinae.jp/q/163" },
  { title: "Q164(이)라는と(이)란の使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/164" },
  { title: "Q165「-야지」と「-야겠다」の違いについて教えてください。", url: "https://kotae.mirinae.jp/q/165" },
  { title: "Q166마음이 속상하다と마음이 불편하다の違いは？", url: "https://kotae.mirinae.jp/q/166" },
  { title: "Q167얼마예요? と얼마짜리예요?の違いについて教えてください。", url: "https://kotae.mirinae.jp/q/167" },
  { title: "Q168～던데요,～더라고요,～더군요はどんな意味ですか。", url: "https://kotae.mirinae.jp/q/168" },
  { title: "Q169(으)면 /-면 /다면 はどう違いますか。", url: "https://kotae.mirinae.jp/q/169" },
  { title: "Q170~바と ~데の違いを教えてください。", url: "https://kotae.mirinae.jp/q/170" },
  { title: "Q171｢前｣ 앞と전、｢後｣ 뒤と후、｢内｣ 안과내はどう違いますか。", url: "https://kotae.mirinae.jp/q/171" },
  { title: "Q172「-면서」は「～ながら」以外に他の意味もありますか？", url: "https://kotae.mirinae.jp/q/172" },
  { title: "Q173「주다, 드리다」の前に来る「-아・어다가」と「-아・어」の違いを教えてください。", url: "https://kotae.mirinae.jp/q/173" },
  { title: "Q174덜~ VS 아직 안~ VS 더~の使い分けは？", url: "https://kotae.mirinae.jp/q/174" },
  { title: "Q175あらゆる連体形について教えてください。", url: "https://kotae.mirinae.jp/q/175" },
  { title: "Q176늘이다と늘리다の違いは何ですか。", url: "https://kotae.mirinae.jp/q/176" },
  { title: "Q177'적합하다'と '적절하다'の違いは何ですか?", url: "https://kotae.mirinae.jp/q/177" },
  { title: "Q178~しても～してもは韓国語で~나 ~나 ですか、~도 ~도 ですか。", url: "https://kotae.mirinae.jp/q/178" },
  { title: "Q179助詞「의」が、省略できる場合とできない場合を教えてください。", url: "https://kotae.mirinae.jp/q/179" },
  { title: "Q180ㄴ단 말이야, 단 말이야の表現について教えてください。", url: "https://kotae.mirinae.jp/q/180" },
  { title: "Q181[까지],[조차],[마저]の使い分けを教えてください。", url: "https://kotae.mirinae.jp/q/181" },
  { title: "Q182쓰러지다と무너지다の違いは？", url: "https://kotae.mirinae.jp/q/182" },
  { title: "Q183처음VS처음으로VS 처음에の使い分けは？", url: "https://kotae.mirinae.jp/q/183" },
  { title: "Q184기분 나빠요 は 気分が悪いという意味ですか、不愉快 という意味ですか？", url: "https://kotae.mirinae.jp/q/184" },
  { title: "Q185日本語の「気」を使った表現について教えてください。", url: "https://kotae.mirinae.jp/q/185" },
  { title: "Q186複数を表す~들の使い方について教えてください。", url: "https://kotae.mirinae.jp/q/186" },
  { title: "Q187形容詞の場合-던vs-았/었던の違いは？", url: "https://kotae.mirinae.jp/q/187" },
];
